### ISSUE TITLE
Appdaemon is broken

### ISSUE THREAD

**Issue by ludeeus** [home-assistant/hassbian-scripts#142]
**Hassbian-config version (`hassbian-config -V`):**  0.8.0
**Script/Suite:** AppDaemon

**Description of problem:**  
AppDaemon does not start after installation.

**Traceback/log (if applicable):**
```bash
pi@hassbian:~ $ sudo service appdaemon@homeassistant status
● appdaemon@homeassistant.service - AppDaemon
   Loaded: loaded (/etc/systemd/system/appdaemon@homeassistant.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Fri 2018-03-23 09:11:01 UTC; 17s ago
  Process: 24493 ExecStart=/srv/appdaemon/bin/appdaemon -c /home/homeassistant/appdaemon/ (code=exited, status=0/SUCCESS)
 Main PID: 24493 (code=exited, status=0/SUCCESS)

Mar 23 09:10:56 hassbian systemd[1]: Started AppDaemon.
Mar 23 09:11:00 hassbian appdaemon[24493]: ERROR no 'appdaemon' section in /home/homeassistant/appdaemon/appdaemon.yaml
```

**Comment by ludeeus** [comment]
I have tested the PR for this in #140 but it gives an error if the key is blank:
```
Mar 23 09:20:25 hassbian systemd[1]: Started AppDaemon.
Mar 23 09:20:29 hassbian appdaemon[25096]: 2018-03-23 09:20:29.775360 INFO AppDaemon Version 3.0.0 starting
Mar 23 09:20:29 hassbian appdaemon[25096]: 2018-03-23 09:20:29.776336 INFO Configuration read from: /home/homeassistant/appdaemon/appdaemon.yaml
Mar 23 09:20:29 hassbian appdaemon[25096]: 2018-03-23 09:20:29.779874 INFO AppDaemon: Starting Apps
Mar 23 09:20:29 hassbian appdaemon[25096]: 2018-03-23 09:20:29.790428 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
Mar 23 09:20:29 hassbian appdaemon[25096]: 2018-03-23 09:20:29.849476 INFO AppDaemon: HASS: HASS Plugin Initializing
Mar 23 09:20:29 hassbian appdaemon[25096]: 2018-03-23 09:20:29.851053 INFO AppDaemon: HASS: HASS Plugin initialization complete
Mar 23 09:20:29 hassbian appdaemon[25096]: 2018-03-23 09:20:29.852534 INFO Dashboards are disabled
Mar 23 09:20:29 hassbian appdaemon[25096]: 2018-03-23 09:20:29.853267 INFO API is disabled
Mar 23 09:20:29 hassbian appdaemon[25096]: 2018-03-23 09:20:29.879041 INFO AppDaemon: HASS: Connected to Home Assistant 0.65.5
Mar 23 09:20:29 hassbian appdaemon[25096]: 2018-03-23 09:20:29.898983 WARNING AppDaemon: ------------------------------------------------------------
Mar 23 09:20:29 hassbian appdaemon[25096]: 2018-03-23 09:20:29.899847 WARNING AppDaemon: Unexpected error during notify_plugin_started()
Mar 23 09:20:29 hassbian appdaemon[25096]: 2018-03-23 09:20:29.900564 WARNING AppDaemon: ------------------------------------------------------------
Mar 23 09:20:29 hassbian appdaemon[25096]: 2018-03-23 09:20:29.916355 WARNING AppDaemon: Traceback (most recent call last):
Mar 23 09:20:29 hassbian appdaemon[25096]:   File "/srv/appdaemon/lib/python3.5/site-packages/appdaemon/appdaemon.py", line 1245, in notify_plugin_started
Mar 23 09:20:29 hassbian appdaemon[25096]:     meta = await self.plugin_objs[namespace].get_metadata()
Mar 23 09:20:29 hassbian appdaemon[25096]:   File "/srv/appdaemon/lib/python3.5/site-packages/appdaemon/plugins/hass/hassplugin.py", line 109, in get_metadata
Mar 23 09:20:29 hassbian appdaemon[25096]:     return await self.get_hass_config()
Mar 23 09:20:29 hassbian appdaemon[25096]:   File "/srv/appdaemon/lib/python3.5/site-packages/appdaemon/plugins/hass/hassplugin.py", line 321, in get_hass_config
Mar 23 09:20:29 hassbian appdaemon[25096]:     r = await self.session.get(apiurl, headers=headers, verify_ssl=self.cert_verify)
Mar 23 09:20:29 hassbian appdaemon[25096]:   File "/srv/appdaemon/lib/python3.5/site-packages/aiohttp/helpers.py", line 109, in __await__
Mar 23 09:20:29 hassbian appdaemon[25096]:     ret = yield from self._coro
Mar 23 09:20:29 hassbian appdaemon[25096]:   File "/srv/appdaemon/lib/python3.5/site-packages/aiohttp/client.py", line 275, in _request
Mar 23 09:20:29 hassbian appdaemon[25096]:     resp = req.send(conn)
Mar 23 09:20:29 hassbian appdaemon[25096]:   File "/srv/appdaemon/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 463, in send
Mar 23 09:20:29 hassbian appdaemon[25096]:     writer.write_headers(status_line, self.headers)
Mar 23 09:20:29 hassbian appdaemon[25096]:   File "/srv/appdaemon/lib/python3.5/site-packages/aiohttp/http_writer.py", line 247, in write_headers
Mar 23 09:20:29 hassbian appdaemon[25096]:     [k + SEP + v + END for k, v in headers.items()])
Mar 23 09:20:29 hassbian appdaemon[25096]:   File "/srv/appdaemon/lib/python3.5/site-packages/aiohttp/http_writer.py", line 247, in <listcomp>
Mar 23 09:20:29 hassbian appdaemon[25096]:     [k + SEP + v + END for k, v in headers.items()])
Mar 23 09:20:29 hassbian appdaemon[25096]: TypeError: Can't convert 'NoneType' object to str implicitly
Mar 23 09:20:29 hassbian appdaemon[25096]: 2018-03-23 09:20:29.917241 WARNING AppDaemon: ------------------------------------------------------------
Mar 23 09:20:29 hassbian appdaemon[25096]: Unclosed connection
Mar 23 09:20:29 hassbian appdaemon[25096]: client_connection: Connection<ConnectionKey(host='127.0.0.1', port=8123, ssl=False)>
Mar 23 09:20:31 hassbian appdaemon[25096]: 2018-03-23 09:20:31.879379 ERROR AppDaemon: Required attribute not set or obtainable from any plugin: latitude
Mar 23 09:20:31 hassbian appdaemon[25096]: 2018-03-23 09:20:31.880243 ERROR AppDaemon: AppDaemon is terminating
Mar 23 09:20:31 hassbian appdaemon[25096]: 2018-03-23 09:20:31.887160 ERROR AppDaemon: Required attribute not set or obtainable from any plugin: longitude
Mar 23 09:20:31 hassbian appdaemon[25096]: 2018-03-23 09:20:31.890151 ERROR AppDaemon: AppDaemon is terminating
Mar 23 09:20:31 hassbian appdaemon[25096]: 2018-03-23 09:20:31.893103 ERROR AppDaemon: Required attribute not set or obtainable from any plugin: elevation
Mar 23 09:20:31 hassbian appdaemon[25096]: 2018-03-23 09:20:31.896186 ERROR AppDaemon: AppDaemon is terminating
Mar 23 09:20:31 hassbian appdaemon[25096]: 2018-03-23 09:20:31.899077 ERROR AppDaemon: Required attribute not set or obtainable from any plugin: time_zone
Mar 23 09:20:31 hassbian appdaemon[25096]: 2018-03-23 09:20:31.901920 ERROR AppDaemon: AppDaemon is terminating
Mar 23 09:20:31 hassbian appdaemon[25096]: 2018-03-23 09:20:31.906338 INFO AppDaemon: HASS: Disconnecting from Home Assistant
Mar 23 09:20:31 hassbian appdaemon[25096]: 2018-03-23 09:20:31.907786 INFO AppDeamon Exited
```
