### ISSUE TITLE
How to remove home assistant platform from homebridge

### ISSUE THREAD

**Issue by phathak** [home-assistant/hassbian-scripts#179]
**Hassbian-config version (`hassbian-config -V`):**  
0.9.1
**Script/Suite:**
homebridge
**Description of problem:**  
How to uninstall?

**Additional info:**
I'd like to know how I can completely remove the home assistant platform from homebridge. It does not appear in my config but when I run it, it still loads it. I've deleted the homebridge user as well as it's home directory.

My config.json :
`{
    "bridge": {
        "name": "Homebridge",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 11111,
        "pin": "XXX-XX-XXX"
    },
    "description": "This is an example configuration file to help you get set up with homebridge-rcswitch-gpiomem.",
    "accessories": [
        {
            "accessory": "RCSwitch",
            "name": "Switch number one",
            "onCode": 1234567,
            "offCode": 2345678,
            "pin": 17,
            "protocol": 1,
            "pulseLength": 190,
            "bitLength": 24,
            "repeats": 10
        }
    ]
}`

homebridge output : 
`[2018-8-17 16:47:40] Loaded config.json with 1 accessories and 0 platforms.
[2018-8-17 16:47:40] ---
[2018-8-17 16:47:41] Loaded plugin: homebridge-homeassistant
[2018-8-17 16:47:42] Registering platform 'homebridge-homeassistant.HomeAssistant'
[2018-8-17 16:47:42] ---
[2018-8-17 16:47:42] Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:64
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'RCSwitch' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:285:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)`

**Comment by phathak** [comment]
Found it. Need to remove this folder :
`/usr/local/lib/node_modules/homebridge-homeassistant`
